# Generated by Django 5.1.4 on 2024-12-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='Label',
            new_name='label',
        ),
    ]
