# Generated by Django 5.2.4 on 2025-08-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuitem_order_orderitem_delete_draw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modifications',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
