# Generated by Django 5.2.4 on 2025-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='pickup', max_length=32),
            preserve_default=False,
        ),
    ]
