# Generated by Django 5.2.4 on 2025-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_booking_time_order_no_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
