# Generated by Django 5.2.4 on 2025-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_booking_time_alter_order_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='1234567890', max_length=20),
            preserve_default=False,
        ),
    ]
