# Generated by Django 5.2.4 on 2026-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='conversation',
            field=models.JSONField(default=list),
        ),
    ]
