# Generated by Django 5.1.4 on 2024-12-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=20)),
                ('winner', models.BooleanField(default=False)),
                ('picture', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='UniqueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prize', verbose_name='Prize')),
            ],
        ),
    ]
