# Generated by Django 5.2.4 on 2025-08-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_groups_useraccount_is_staff_and_more'),
        ('core', '0008_category_restaurant_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.restaurant'),
        ),
    ]
